apiVersion: 1
datasources:
  - name: QuestDB
    uid: questdb
    type: grafana-postgresql-datasource
    access: proxy
    url: 211.181.122.102:8812
    user: admin
    isDefault: true
    editable: true
    jsonData:
      database: qdb
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 8
      maxIdleConns: 4
      connMaxLifetime: 14400
    secureJsonData:
      password: quest
